Require seq
[   21s] Command [7] exited with code 2:
[   21s] $ (cd _build/default && /usr/bin/ocamlc.opt -w -40 -w -3-6-27-34-50 -g -bin-annot -I src/.fmt.objs/byte -I /usr/lib64/ocaml/result -I /usr/lib64/ocaml/stdlib-shims -no-alias-deps -o src/.fmt.objs/byte/fmt.cmi -c -intf src/fmt.mli)
[   21s] File "src/fmt.mli", line 290, characters 36-41:
[   21s] Error: Unbound module Seq

Signed-off-by: Olaf Hering <olaf@aepfle.de>